name: diamon_rose_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.18

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  app_tracking_transparency: ^2.0.2+1
  audio_video_progress_bar: ^0.10.0
  aws_s3_upload: ^1.2.0
  badges: ^2.0.1
  blurrycontainer: ^1.0.2
  # buttons_tabbar: ^1.3.4
  cached_network_image: ^3.1.0
  cached_video_player: ^2.0.3
  camera: ^0.10.0
  chewie: ^1.1.0
  cloud_firestore: ^3.4.4
  connectivity: ^3.0.6
  cool_alert: ^1.1.0
  country_code_picker: ^2.0.2
  country_pickers: ^2.0.0
  crawl_splash: ^0.1.0
  cupertino_icons: ^1.0.3
  custom_navigation_bar: ^0.8.2
  date_time_picker: ^2.1.0
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  dotted_border: ^2.0.0+2
  dropdown_search: ^3.0.1
  email_auth: ^1.0.0
  eva_icons_flutter: ^3.1.0
  extended_image: ^6.1.0
  # ffmpeg_kit_flutter: ^4.5.1
  ffmpeg_kit_flutter_https_gpl: ^4.5.1
  file_picker: ^4.2.3
  # firebase_app_check: ^0.0.6+9
  firebase_auth: ^3.3.11
  firebase_core: ^1.20.0
  firebase_dynamic_links: ^4.3.3
  firebase_messaging: ^12.0.1
  firebase_storage: ^10.2.9
  fl_chart: ^0.55.0
  flick_video_player: ^0.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_cache_manager: ^3.1.3
  flutter_datetime_picker: ^1.5.1
  flutter_easyloading: ^3.0.3
  flutter_facebook_auth: ^4.4.1
  flutter_gif: ^0.0.4
  flutter_inappwebview: ^5.4.3+7
  flutter_local_notifications: ^9.4.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_paypal: ^0.0.8
  flutter_speed_dial: ^6.0.0
  flutter_staggered_grid_view: ^0.6.1
  # flutter_stripe: 4.0.0 #removing stripe from devices
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  get: ^4.3.8
  get_it: ^7.2.0
  global_configuration: ^2.0.0-nullsafety.0
  # google_ml_kit: ^0.12.0
  google_sign_in: ^5.2.4
  helpers: ^1.1.4
  http: ^0.13.4
  image_cropper: ^2.0.3
  image_editor: ^1.0.2
  image_frame_animation: ^0.0.1
  image_picker: ^0.8.4+11
  image_sequence_animator: ^2.0.0
  injectable: ^1.5.3
  intl: ^0.17.0-nullsafesty
  intl_generator: ^0.2.0+0
  just_audio: ^0.9.21
  loading_overlay: ^0.3.0
  logger: ^1.1.0
  lottie: ^1.2.2
  mailer: ^5.1.1
  multi_select_flutter: ^4.1.2
  nanoid: ^1.0.0
  package_info_plus: ^1.0.6
  page_transition: ^2.0.5
  path_provider: ^2.0.5
  pay: ^1.0.1
  permission_handler: 9.2.0
  persistent_bottom_nav_bar: ^4.0.2
  photo_view: ^0.14.0
  pin_code_fields: ^7.3.0
  pinput: ^2.2.0
  preload_page_view: ^0.1.6
  provider: ^6.0.2
  rxdart: ^0.27.2
  share_plus: ^4.0.10
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  simple_s3: ^0.3.2
  simple_tooltip: ^1.0.0
  sizer: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  spring_button: ^2.0.0
  sqflite: ^2.0.2+1
  stacked: ^2.3.3
  system_info_plus: ^0.0.5
  text_scroll: ^0.1.0
  the_apple_sign_in: ^1.1.1
  timeago: ^3.2.2
  toggle_switch: ^2.0.1
  top_snackbar_flutter: ^2.1.1
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.20
  uuid: ^3.0.4
  video_player: ^2.2.6
  video_thumbnail: ^0.5.0
  visibility_detector: ^0.2.2
  widget_circular_animator: ^1.0.0

dev_dependencies:
  build_runner: any
  flutter_gen_runner: null
  flutter_lints: any
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.0
  pedantic: ^1.11.1
  flutter_launcher_icons: "^0.9.3"
  freezed: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/GDapplogo.png"

flutter_native_splash:
  background_image: "assets/images/png/app_background.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/static/
    - assets/images/
    - assets/images/gif/
    - assets/images/png/
    - assets/images/svg/
    - assets/animations/
    - assets/arViewer/
    - assets/default_payment_profile_apple.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TikTokIcons
      fonts:
        - asset: assets/fonts/TikTokIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
